language: python
python:
 - "2.7"
branches:
  only:
  - master
env:
  - APP_DEBUG=false
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python3.2 python2.7
- openssl aes-256-cbc -K $encrypted_a417267c90b2_key -iv $encrypted_a417267c90b2_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
script: ./run_build.sh
# install:
# - npm i docsify-cli -g
# - npm install
# - git clone https://github.com/zoeminghong/full-stack.git
addons:
  ssh_known_hosts: 67.209.184.19
after_success:
- ssh root@67.209.184.19 -p 29869 -o StrictHostKeyChecking=no 'cd /etc/nginx/www &&
  git pull'
